# kayzels
\addfile[input]{<filename>}
\addfile{<filename>}
\begin{example}
\begin{exercise}{title}
\begin{sidenote}{title}
\begin{indentparagraph}
\begin{subproof}
\begin{subproof}[name]
\begin{theorem}
\begin{theorem}[title]
\end{example}
\end{exercise}
\end{sidenote}
\end{indentparagraph}
\end{subproof}
\end{theorem}
\rulebookend
\rulechapterend